{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "2f4f611b-5a90-4edd-9469-9efc2ad1d673",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   VendorNumber                VendorName  Brand              Description  \\\n",
      "0          1128         BROWN-FORMAN CORP   1233  Jack Daniels No 7 Black   \n",
      "1          4425     MARTIGNETTI COMPANIES   3405    Tito's Handmade Vodka   \n",
      "2         17035         PERNOD RICARD USA   8068         Absolut 80 Proof   \n",
      "3          3960  DIAGEO NORTH AMERICA INC   4261   Capt Morgan Spiced Rum   \n",
      "4          3960  DIAGEO NORTH AMERICA INC   3545          Ketel One Vodka   \n",
      "\n",
      "   PurchasePrice  ActualPrice  Volume  TotalPurchaseQuantity  \\\n",
      "0          26.27        36.99  1750.0                 145080   \n",
      "1          23.19        28.99  1750.0                 164038   \n",
      "2          18.24        24.99  1750.0                 187407   \n",
      "3          16.17        22.99  1750.0                 201682   \n",
      "4          21.89        29.99  1750.0                 138109   \n",
      "\n",
      "   TotalPurchaseDollars  TotalSalesQuantity  TotalSalesDollars  \\\n",
      "0            3811251.60             45430.0         1657105.70   \n",
      "1            3804041.22             47714.0         1448558.82   \n",
      "2            3418303.68             59446.0         1491934.04   \n",
      "3            3261197.94             91846.0         2058278.54   \n",
      "4            3023206.01             46047.0         1454691.53   \n",
      "\n",
      "   TotalSalesPrice  TotalExciseTax  FreightCost  GrossProfit  ProfitMargin  \n",
      "0        283398.43        83471.27     68601.68  -2154145.90   -129.994478  \n",
      "1        233682.22        87668.41    144929.24  -2355482.40   -162.608682  \n",
      "2        197824.33       109225.18    123780.22  -1926369.64   -129.118955  \n",
      "3        184272.78       168760.46    257032.07  -1202919.40    -58.442984  \n",
      "4        226983.47        84605.46    257032.07  -1568514.48   -107.824542  \n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import sqlite3\n",
    "from sqlalchemy import create_engine\n",
    "import logging\n",
    "# Assuming ingest_db is in your ingestion.py file\n",
    "from Ingestion_db import ingest_db \n",
    "\n",
    "def create_vendor_summary(conn):\n",
    "    '''Merges tables using CTEs to create a vendor summary.'''\n",
    "    # Note: I added the JOIN to purchase_prices (pp) so pp.Price and pp.Volume work\n",
    "    query = \"\"\"\n",
    "    WITH FreightSummary AS (\n",
    "        SELECT VendorNumber, SUM(Freight) AS FreightCost\n",
    "        FROM vendor_invoice\n",
    "        GROUP BY VendorNumber\n",
    "    ),\n",
    "    PurchaseSummary AS (\n",
    "        SELECT\n",
    "            p.VendorNumber, p.VendorName, p.Brand, p.Description,\n",
    "            p.PurchasePrice,\n",
    "            pp.Price AS ActualPrice,\n",
    "            pp.Volume,\n",
    "            SUM(p.Quantity) AS TotalPurchaseQuantity,\n",
    "            SUM(p.Dollars) AS TotalPurchaseDollars\n",
    "        FROM purchases p\n",
    "        LEFT JOIN purchase_prices pp ON p.Brand = pp.Brand \n",
    "        WHERE p.PurchasePrice > 0\n",
    "        GROUP BY p.VendorNumber, p.VendorName, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume\n",
    "    ),\n",
    "    SalesSummary AS (\n",
    "        SELECT\n",
    "            VendorNo, Brand,\n",
    "            SUM(SalesQuantity) AS TotalSalesQuantity,\n",
    "            SUM(SalesDollars) AS TotalSalesDollars,\n",
    "            SUM(SalesPrice) AS TotalSalesPrice,\n",
    "            SUM(ExciseTax) AS TotalExciseTax\n",
    "        FROM sales\n",
    "        GROUP BY VendorNo, Brand\n",
    "    )\n",
    "    SELECT\n",
    "        ps.*,\n",
    "        ss.TotalSalesQuantity, ss.TotalSalesDollars,\n",
    "        ss.TotalSalesPrice, ss.TotalExciseTax,\n",
    "        fs.FreightCost\n",
    "    FROM PurchaseSummary ps\n",
    "    LEFT JOIN SalesSummary ss ON ps.VendorNumber = ss.VendorNo AND ps.Brand = ss.Brand\n",
    "    LEFT JOIN FreightSummary fs ON ps.VendorNumber = fs.VendorNumber\n",
    "    ORDER BY ps.TotalPurchaseDollars DESC\n",
    "    \"\"\"\n",
    "    return pd.read_sql_query(query, conn)\n",
    "\n",
    "def clean_data(df):\n",
    "    '''Cleans data and calculates business KPIs.'''\n",
    "    # 1. Handle Volume\n",
    "    df['Volume'] = df['Volume'].replace('Unknown', 0).astype(float)\n",
    "    \n",
    "    # 2. Fill missing sales/freight with 0\n",
    "    df.fillna(0, inplace=True)\n",
    "\n",
    "    # 3. Clean strings\n",
    "    df['VendorName'] = df['VendorName'].str.strip()\n",
    "    df['Description'] = df['Description'].str.strip()\n",
    "    \n",
    "    # 4. KPI Calculations (Using correct column names from the SQL query)\n",
    "    # Gross Profit = Sales - Cost of Goods (TotalPurchaseDollars is used here as cost proxy)\n",
    "    df['GrossProfit'] = df['TotalSalesDollars'] - df['TotalPurchaseDollars']\n",
    "    \n",
    "    # Avoid division by zero for margins\n",
    "    df['ProfitMargin'] = (df['GrossProfit'] / df['TotalSalesDollars'].replace(0, 1)) * 100\n",
    "    \n",
    "    return df\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    conn = sqlite3.connect('inventory.db')\n",
    "    \n",
    "    logging.info('Creating Vendor Summary Table...')\n",
    "    summary_df = create_vendor_summary(conn)\n",
    "    \n",
    "    logging.info('Cleaning Data and calculating KPIs...')\n",
    "    clean_df = clean_data(summary_df)\n",
    "    \n",
    "    # To see your results in the notebook:\n",
    "    print(clean_df.head())\n",
    "    \n",
    "    # Close connection\n",
    "    conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4295f403-67ce-47c8-8686-4dd269d265f5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
